---
- name: Generate self-signed certificates for the optional internal TLS tests
  ansible.builtin.shell:
    cmd: >
     . {{ kolla_ansible_venv_path }}/bin/activate &&
     kolla-ansible certificates
     -i /etc/kolla/inventory
     -vvv
     >/tmp/logs/ansible/upgrade-certificates 2>&1

# NOTE(mnasiadka): Need to run bootstrap before upgrade
- name: Run kolla-ansible bootstrap-servers
  ansible.builtin.shell:
    cmd: >
     . {{ kolla_ansible_venv_path }}/bin/activate &&
     kolla-ansible bootstrap-servers
     -i /etc/kolla/inventory
     -vvv
     >/tmp/logs/ansible/upgrade-bootstrap 2>&1

- name: Run kolla-ansible prechecks
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible prechecks
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/upgrade-prechecks 2>&1

- name: Run kolla-ansible pull
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible pull
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/upgrade-pull 2>&1

- name: Run kolla-ansible upgrade
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible upgrade
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/upgrade 2>&1

- name: Run kolla-ansible post-deploy
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible post-deploy
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/upgrade-post-deploy 2>&1

- name: Run kolla-ansible validate-config on upgrades
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible validate-config
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/upgrade-validate-config 2>&1

