---
- name: Ensuring config directories exist
  vars:
    service_name: "{{ item.0.service_name }}"
    service: "{{ common_services[service_name] }}"
  file:
    path: "{{ node_config_directory }}/{{ item.1 }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  with_subelements:
    - - service_name: "kolla-toolbox"
        paths:
          - "kolla-toolbox"
    - paths
  when: service | service_enabled_and_mapped_to_host

- include_tasks: copy-certs.yml
  when:
    - common_copy_certs | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  with_dict: "{{ common_services | select_services_enabled_and_mapped_to_host }}"

- name: Ensure RabbitMQ Erlang cookie exists
  become: true
  template:
    src: "rabbitmq-erlang.cookie.j2"
    dest: "{{ node_config_directory }}/kolla-toolbox/rabbitmq-erlang.cookie"
    mode: "0660"
  when:
    - common_services['kolla-toolbox'] | service_enabled_and_mapped_to_host
    - enable_rabbitmq | bool

- name: Ensuring config directories have correct owner and permission
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - item.key != "kolla-toolbox"
  with_dict: "{{ common_services | select_services_enabled_and_mapped_to_host }}"

- name: Copy rabbitmq-env.conf to kolla toolbox
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/kolla-toolbox/rabbitmq-env.conf"
    mode: "0600"
  with_first_found:
    - "{{ node_custom_config }}/kolla-toolbox/{{ inventory_hostname }}/rabbitmq-env.conf"
    - "{{ node_custom_config }}/kolla-toolbox/rabbitmq-env.conf"
    - "rabbitmq-env.conf.j2"
  become: true
  when:
    - common_services['kolla-toolbox'] | service_enabled_and_mapped_to_host
    - enable_rabbitmq | bool

- name: Copy rabbitmq erl_inetrc to kolla toolbox
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/kolla-toolbox/erl_inetrc"
    mode: "0600"
  become: true
  with_first_found:
    - "{{ node_custom_config }}/kolla-toolbox/{{ inventory_hostname }}/erl_inetrc"
    - "{{ node_custom_config }}/kolla-toolbox/erl_inetrc"
    - "erl_inetrc.j2"
  when:
    - common_services['kolla-toolbox'] | service_enabled_and_mapped_to_host
    - enable_rabbitmq | bool
