---
- project:
    queue: kolla
    templates:
      - ansible-role-jobs
      - check-requirements
      - kolla-ansible-scenario-aio
      - kolla-ansible-scenario-bifrost
      - kolla-ansible-scenario-cells
      - kolla-ansible-scenario-cephadm
      # NOTE(mnasiadka): Failing since
      # https://review.opendev.org/c/openstack/kolla-ansible/+/864780
      # - kolla-ansible-scenario-container-engine-migration
      - kolla-ansible-scenario-haproxy-fqdn
      - kolla-ansible-scenario-kayobe
      - kolla-ansible-scenario-openbao
      - kolla-ansible-scenario-kvm
      - kolla-ansible-scenario-lets-encrypt
      - kolla-ansible-scenario-magnum
      - kolla-ansible-scenario-mariadb
      - kolla-ansible-scenario-masakari
      - kolla-ansible-scenario-nfv
      - kolla-ansible-scenario-ironic
      # NOTE(mnasiadka): All runs end up with DISK_FULL
      #- kolla-ansible-scenario-ipv6
      - kolla-ansible-scenario-octavia
      - kolla-ansible-scenario-ovn
      - kolla-ansible-scenario-prometheus-opensearch
      # NOTE(mnasiadka): SSO and non-SSO tests are failing
      #- kolla-ansible-scenario-skyline
      - kolla-ansible-scenario-telemetry
      - openstack-cover-jobs
      - openstack-python3-jobs-kolla-ansible
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
