---
- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  with_dict: "{{ heat_services | select_services_enabled_and_mapped_to_host }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: heat_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/heat/"
      skip: true

- name: Set heat policy file
  set_fact:
    heat_policy_file: "{{ heat_policy.results.0.stat.path | basename }}"
    heat_policy_file_path: "{{ heat_policy.results.0.stat.path }}"
  when:
    - heat_policy.results | length > 0

- include_tasks: copy-certs.yml
  when:
    - heat_copy_certs | bool

- name: Copying over config.json files for services
  become: true
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  with_dict: "{{ heat_services | select_services_enabled_and_mapped_to_host }}"

- name: Copying over heat.conf
  become: true
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/heat.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/heat.conf"
      - "{{ node_custom_config }}/heat/{{ item.key }}.conf"
      - "{{ node_custom_config }}/heat/{{ inventory_hostname }}/heat.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/heat.conf"
    mode: "0660"
  with_dict: "{{ heat_services | select_services_enabled_and_mapped_to_host }}"

- name: Copying over existing policy file
  become: true
  template:
    src: "{{ heat_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ heat_policy_file }}"
    mode: "0660"
  when:
    - heat_policy_file is defined
  with_dict: "{{ heat_services | select_services_enabled_and_mapped_to_host }}"

- name: Copying over heat-api wsgi config
  vars:
    service: "{{ heat_services['heat-api'] }}"
  template:
    src: "{{ role_path }}/templates/wsgi-heat-api.conf.j2"
    dest: "{{ node_config_directory }}/heat-api/wsgi-heat-api.conf"
    mode: "0660"
  become: true
  when:
    - service | service_enabled_and_mapped_to_host
    - heat_wsgi_provider == "apache"

- name: Configure uWSGI for heat-api
  include_role:
    name: service-uwsgi-config
  vars:
    project_services: "{{ heat_services }}"
    service: "{{ heat_services['heat-api'] }}"
    service_name: "heat-api"
    service_uwsgi_config_http_port: "{{ heat_api_listen_port }}"
    service_uwsgi_config_log_file_chmod: "644"
    service_uwsgi_config_module: "{{ service.wsgi }}"
    service_uwsgi_config_tls_backend: "{{ heat_enable_tls_backend | bool }}"
    service_uwsgi_config_tls_cert: "/etc/heat/certs/heat-cert.pem"
    service_uwsgi_config_tls_key: "/etc/heat/certs/heat-key.pem"
    service_uwsgi_config_uid: "heat"
  when:
    - service | service_enabled_and_mapped_to_host
    - heat_wsgi_provider == "uwsgi"

- name: Copying over heat-api-cfn wsgi config
  vars:
    service: "{{ heat_services['heat-api-cfn'] }}"
  template:
    src: "{{ role_path }}/templates/wsgi-heat-api-cfn.conf.j2"
    dest: "{{ node_config_directory }}/heat-api-cfn/wsgi-heat-api-cfn.conf"
    mode: "0660"
  become: true
  when:
    - service | service_enabled_and_mapped_to_host
    - heat_wsgi_provider == "apache"

- name: Configure uWSGI for heat-api-cfn
  include_role:
    name: service-uwsgi-config
  vars:
    project_services: "{{ heat_services }}"
    service: "{{ heat_services['heat-api-cfn'] }}"
    service_name: "heat-api-cfn"
    service_uwsgi_config_http_port: "{{ heat_api_cfn_listen_port }}"
    service_uwsgi_config_log_file_chmod: "644"
    service_uwsgi_config_module: "{{ service.wsgi }}"
    service_uwsgi_config_tls_backend: "{{ heat_enable_tls_backend | bool }}"
    service_uwsgi_config_tls_cert: "/etc/heat/certs/heat-cert.pem"
    service_uwsgi_config_tls_key: "/etc/heat/certs/heat-key.pem"
    service_uwsgi_config_uid: "heat"
  when:
    - service | service_enabled_and_mapped_to_host
    - heat_wsgi_provider == "uwsgi"
